### ISSUE TITLE
Pospájať časti KP do jednotného dokumentu

### ISSUE THREAD

**Issue by ondy99** [TIS2023-FMFI/robot-league#12]

**Comment by pavelpetrovic** [comment]
Prikladám môj návrh úprav KP. Prosím prejdite to celé, či to všetko ide/viete urobiť, či tam niečo nechýba, je to konzistentné a jednoznačné. Ďakujem.
[KP_RL.docx](https://github.com/TIS2023-FMFI/robot-league/files/13202162/KP_RL.docx)
